### ISSUE TITLE
Information on user login

### ISSUE THREAD

**Issue by kmatth** [ethankrein/On-Wiz#9]
Hello, I'm currently doing some reverse engineering towards understanding the game's login functionality. The structure of a login DML message is defined as `MSG_USER_AUTHEN_V3` in the `LoginMessages.xml` file of the patch client. User data get transmitted in the `REC1` field.

I initially thought some static analysis could do the trick as I'm not an expert for crypto analysis, but it turns out that this is a tougher challenge than expected because of heavy LTO optimizations hitting in. From what it seems, the REC1 algorithm involves both, an encryption and a hashing mechanism, performed on a combination of session id, username and password.

I'd be happy to learn more about it if someone has details to share. I'm also available on Discord as `MattK#0817` for a more direct chat, just shoot me a friend request.

**Comment by latelylk** [comment]
This should be all of the information contained within that message.

```yaml
serviceId: 7
serviceType: LOGIN
messageId: 27
messageType: MSG_USER_AUTHEN_V3
Description: "User Authentication Request Message."

Fields:
  Rec1: 
  Version: 
  Revision: 
  DataRevision: 
  CRC: 
  MachineID: 
  Locale: 
  PatchClientID: 
  IsSteamPatcher: 
```

Info pulled from LoginMessages.xml located in the Root WAD:
![image](https://user-images.githubusercontent.com/33592564/100021858-c30b0600-2da7-11eb-8335-172eb856524c.png)

I haven't touched LoginMessages in awhile, but as far as I know they're serialized in the same manner as all of the other messages. Rec1 should be in a byte string format. I don't have information on how exactly Rec1 is generated, but I wish you luck in discovering the formula.
